config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  get 'my_listings', to: 'listings#my_listings'
  get 'my_listings/:id', to: 'listings#my_listings_show', as: 'my_listings_show'
  get 'profile', to: 'users#display'
  get 'profile/settings', to:  'users#settings'

  resources :listings do
    resources :bookings, only: :create
  end

  resources :bookings, only: %i[index show edit update destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :listing
  has_one :review

  validate :end_date_after_start_date, :start_date_valid?, :end_date_valid?

  private

  def end_date_after_start_date
    errors.add(:end_date, "Ending date of booking must be after the Starting date") if end_date < start_date
  end

  def start_date_valid?
    errors.add(:start_date, "Starting date of booking cannot be before Listing opens") if start_date < listing.start_date
  end

  def end_date_valid?
    errors.add(:end_date, "Ending date of booking cannot be after Listing closes") if listing.end_date < end_date
  end
end

app/models/listing.rb
class Listing < ApplicationRecord
  belongs_to :user
  has_many :bookings
  has_one_attached :photo

  include PgSearch::Model
  pg_search_scope :search_by_vehicle_type_and_name,
    against: [ :vehicle_type, :name ],
    using: {
      tsearch: { prefix: false } # <-- now `superman batm` will return something!
    }

  validates :vehicle_type, :name, :description, :street, :zip, :city, :country, :start_date, :end_date, :price, presence: true
  validates :description, length: { minimum: 15, too_short: "Please add a more detailed description" }
  validate :end_date_after_start_date

  geocoded_by :address
  after_validation :geocode

  def address
    [street, city, country].compact.join(', ')
  end

  private

  def end_date_after_start_date
    errors.add(:end_date, "must be after the start date") if end_date < start_date
  end
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :booking
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :listings
  has_many :bookings

  validates :first_name, :last_name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: %i[first_name last_name tel])
    devise_parameter_sanitizer.permit(:account_update, keys: %i[first_name last_name tel])
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :set_listing, only: %i[new create]

  def index
    @bookings = Booking.all.select { |booking| booking.user == current_user }
  end

  def show
    @booking = Booking.find(params[:id])
  end

  def new
    @booking = Booking.new
    # @listing = Listing.find(params[:listing_id])
  end

  def create
    @booking = Booking.new(booking_params)
    @listing = Listing.find(params[:listing_id])
    @booking.listing = @listing
    @booking.user = current_user
    if @booking.save
      redirect_to bookings_path
      flash[:notice] = 'Your Booking was successfully created   🚀🚀🚀'
      # render html: "<script>alert('No vv users!')</script>".html_safe
    else
      # redirect_to @listing
      flash[:notice] = 'A Problem appeared. Please check your form or login status'
      render 'listings/show'
      # render html: "<script>alert('No users!')</script>".html_safe
    end
  end

  def edit
    @booking = Booking.find(params[:id])
  end

  def update
    @booking = Booking.find(params[:id])
    if @booking.update(booking_params)
      redirect_to bookings_path, notice: 'Booking was updated'
    else
      render :edit
    end
  end

  def destroy
    @booking = Booking.find(params[:id])
    @booking.destroy
    redirect_to bookings_path
  end

  private

  def set_listing
    @listing = Listing.find(params[:listing_id])
  end

  def booking_params
    params.require(:booking).permit(:start_date, :end_date)
  end
end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController
  def index
    @listings = user_signed_in? ? Listing.all.geocoded.reject { |listing| listing.user == current_user } : Listing.all.geocoded

    @markers = @listings.map do |listing|
      {
        lat: listing.latitude,
        lng: listing.longitude,
        infoWindow: render_to_string(partial: "info_window", locals: { listing: listing })
      }
    end
    if params[:query].present?
      @listings = user_signed_in? ? Listing.search_by_vehicle_type_and_name(params[:query]).reject { |listing| listing.user == current_user } : Listing.search_by_vehicle_type_and_name(params[:query])
    else
      @listings = user_signed_in? ? Listing.all.reject { |listing| listing.user == current_user } : Listing.all
    end

  end

  def show
    @listing = Listing.find(params[:id])
    @booking = Booking.new

    @markers = [
      {
        lat: @listing.latitude,
        lng: @listing.longitude
      }
    ]
  end

  def new
    @listing = Listing.new
  end

  def create
    @listing = Listing.new(listing_params)
    @listing.user = current_user
    if @listing.save
      redirect_to my_listings_show_path(@listing), notice: 'Listing was succesfully created 🎊'
    else
      render :new
    end
  end

  def edit
    @listing = Listing.find(params[:id])
  end

  def update
    @listing = Listing.find(params[:id])
    if @listing.update(listing_params)
      redirect_to listing_path(@listing), notice: 'Listing was updated'
    else
      render :edit
    end
  end

  def destroy
    @listing = Listing.find(params[:id])
    @listing.destroy
    redirect_to my_listings_path, notice: 'Listing was removed'
  end

  def my_listings
    @listings = Listing.all.select { |listing| listing.user == current_user }
  end

  def my_listings_show
    @listing = Listing.find(params[:id])
  end

  private

  def set_listing
    @listing = Listing.find(params[:id])
  end

  def listing_params
    params.require(:listing).permit(:vehicle_type, :name, :description, :street, :zip, :city, :country, :start_date, :end_date, :price, :photo)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def display
  end

  def settings
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/_new.html.erb
<%= simple_form_for @booking do |f| %>
<%= f.input :start_date, as: :date, html5: true %>
<%= f.input :end_date, as: :date, html5: true %>
<%= f.submit %>
<% end %>

app/views/bookings/edit.html.erb
<%= simple_form_for @booking do |f| %>
<%= f.input :start_date, as: :date, html5: true %>
<%= f.input :end_date, as: :date, html5: true %>
<%= f.submit %>
<% end %>

app/views/bookings/index.html.erb
<%= render user_signed_in? ? "../views/navbar_loggedin" : "../views/navbar_notloggedin" %>

<% @bookings.each do |booking| %>
  <div class="row align-items-center">
    <div class="col-lg-8">
      <div class="justify-content-around">
        <div class="container-fluid card-container d-flex justify-content-center flex-wrap">
            <a class="card col-7 mx-2 px-0 my-2 border-0" style="text-decoration:none" href="<%= listing_path(booking.listing) %>">
              <img class="card-img-top" src="<%= cl_image_path booking.listing.photo.key %>">
              <div class="card-infos mx-2">
                <div class="row justify-content-between mt-2 mx-1">
                  <h2><%= booking.listing.name %></h2>
                  <div class="row justify-content-between mx-1">
                    <h3 class="mx-1"><%= booking.listing.price %></h3>
                    <h4> €/day</h4>
                  </div>
                </div>
                <div class="row justify-content-between mx-1">
                  <h5><em><%= booking.listing.city %>, <%= booking.listing.country %></em></h5>
                </div>
                <p class="mx-1"><%= booking.listing.description %></p>
              </div>
            </a>
            <div class="d-flex update-listing flex-column">
            </div>
        </div>
      </div>
    </div>
      <div class="col-lg-4">
        <div class="text-left booking-info">
          <h2>Start date </h2>
          <p><%= booking.start_date %></p>
          <h2>End date</h2>
          <p><%= booking.end_date %></p>
          <h2>Total cost: <%= (booking.end_date - booking.start_date).to_i * booking.listing.price %>€</h2>
          <%= link_to "Edit", edit_booking_path(booking), class: "btn btn-gradient" %>
          <%= link_to 'Delete', booking_path(booking), class: "btn btn-gradient", method: :delete, data: { confirm: 'Are you sure you want to delete this booking?' } %>
        </div>
      </div>
  </div>
<% end %>

<%= render "../views/footer" %>

app/views/bookings/new.html.erb
<%= simple_form_for @booking do |f| %>
  <%= f.input :start_date, as: :date, html5: true %>
  <%= f.input :end_date, as: :date, html5: true %>
  <%= f.submit %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Wehicle</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>


    


  </head>

  <body>
      <%= render 'shared/flashes' %>
    <%= yield %>
  </body>
</html>

app/views/listings/_footer.html.erb
<div class="footer mt-3">
  <div class="d-flex justify-content-center mt-5">
    <div class="footer-links">
      <a href="#"><i class="fab fa-github"></i></a>
      <a href="#"><i class="fab fa-instagram"></i></a>
      <a href="#"><i class="fab fa-facebook"></i></a>
      <a href="#"><i class="fab fa-twitter"></i></a>
      <a href="#"><i class="fab fa-linkedin"></i></a>
    </div>
  </div>
  <div class="footer-copyright">
  </div>
</div>

app/views/listings/_info_window.html.erb
<h2><%= listing.name %></h2>
<% if listing.photo.attached? %>
  <img class="card-img-top" style="border-radius: 5px" src="<%= cl_image_path listing.photo.key %>">
  <% end %>
  <p class="mx-1"><%= listing.price %>€/day</p>
<%= link_to 'Book now', listing_path(listing), class: "btn btn-gradient" %>

app/views/listings/edit.html.erb
<%= render user_signed_in? ? "../views/navbar_loggedin" : "../views/navbar_notloggedin" %>

<div class="container">
  <div class="row justify-content-center">
    <div class="col-9 col-lg-6 my-5 text-left">
    <div class="text-center">
  <h1>Edit my WEhicle</h1>
    </div>
  <%= simple_form_for @listing do |f| %>
  <%= f.input :vehicle_type %>
  <%= f.input :name %>
  <%= f.input :description %>
  <%= f.input :street %>
  <%= f.input :zip %>
  <%= f.input :city %>
  <%= f.input :country %>
  <%= f.input :price %>
  <%= f.input :start_date, as: :date, html5: true %>
  <%= f.input :end_date, as: :date, html5: true %>
  <%= f.submit class: "btn btn-gradient" %>
  <% end %>

    </div>
  </div>
</div>

app/views/listings/index.html.erb
<%= render user_signed_in? ? "../views/navbar_loggedin" : "../views/navbar_notloggedin" %>



<div class="d-flex barframe my-3 justify-content-center">
  <%= form_tag listings_path, method: :get, class: "form-inline searchbar" do %>
    <%= text_field_tag :query,
      params[:query],
      class: "form-control", id:"searchbar",
      placeholder: "🔍 Find your dream ride!"
    %>
    <div class="child">
      <%= submit_tag "Search", class: "btn btn-primary" %>
    </div>
<% end %>
</div>


<div>
  <div class="container-fluid card-container d-flex justify-content-center flex-wrap">
    <% @listings.each do |listing| %>
      <a class="card col-3 mx-2 px-0 my-2 border-0" style="text-decoration:none" href="<%= listing_path(listing) %>">
        <% if listing.photo.attached? %>
          <img class="card-img-top" style="height: 300px; object-fit: cover;" src="<%= cl_image_path listing.photo.key %>">
        <% end %>
        <div class="card-infos mx-2">
          <div class="row justify-content-between mt-2 mx-1">
            <h2><%= listing.name %></h2>
            <div class="row justify-content-between mx-1">
              <h3 class="mx-1"><%= listing.price %> €/day</h3>
            </div>
          </div>
          <div class="row justify-content-between mx-1">
            <h5><em><%= listing.city %>, <%= listing.country %></em></h5>
          </div>
          <p class="mx-1"><%= listing.description %></p>
        </div>
      </a>
    <% end %>
  </div>
    <div class="container" id="map"
       style="width: 100%; height: 600px; border-radius: 5px"
       data-markers="<%= @markers.to_json %>"
       data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>">

    </div>
</div>


<%= render "../views/footer" %>

app/views/listings/my_listings.html.erb
<%= render user_signed_in? ? "../views/navbar_loggedin" : "../views/navbar_notloggedin" %>

<div class="container justify-content-around">
  <div class="text-center">
    <a class="btn btn-gradient m-3 align-items-center" href="<%= new_listing_path  %>" >Add new</a>
  </div>
    <div class="container-fluid card-container d-flex justify-content-center flex-wrap">
      <% @listings.each do |listing| %>
        <a class="card col-7 mx-2 px-0 my-2 border-0" style="text-decoration:none" href="my_listings/<%= listing.id %>">
          <img class="card-img-top" src="<%= cl_image_path listing.photo.key %>">
          <div class="card-infos mx-2">
            <div class="row justify-content-between mt-2 mx-1">
              <h2><%= listing.name %></h2>
              <div class="row justify-content-between mx-1">
                <h3 class="mx-1"><%= listing.price %>€</h3>
                <h4>per day</h4>
              </div>
            </div>
            <div class="row justify-content-between mx-1">
              <h5><em><%= listing.city %>, <%= listing.country %></em></h5>
            </div>
            <p class="mx-1"><%= listing.description %></p>
          </div>
        </a>
        <div class="d-flex update-listing flex-column">
          <%= link_to 'Update', edit_listing_path(listing), class: "btn btn-gradient mt-2" %>
          <%= link_to 'Delete', listing_path(listing), class: "btn btn-gradient mt-1", method: :delete, data: { confirm: 'Are you sure you want to delete this listing?' } %>
        </div>
      <% end %>
    </div>
</div>

<%= render "../views/footer" %>

app/views/listings/my_listings_show.html.erb
<%= render user_signed_in? ? "../views/navbar_loggedin" : "../views/navbar_notloggedin" %>


<div class="container">
  <div class="d-flex">
    <div>
      <div class="d-flex justify-content-between">
        <h1 class="mt-3"><%= @listing.name %></h1>
        <div class="d-flex update-listing">
          <%= link_to 'Update', edit_listing_path(@listing), class: "btn btn-gradient mx-2 my-3" %>
          <%= link_to 'Delete', listing_path(@listing), class: "btn btn-gradient mx-2 my-3", method: :delete, data: { confirm: 'Are you sure you want to delete this listing?' } %>
        </div>
      </div>
      <div class="card-trip mt-2">
        <img src="<%= cl_image_path @listing.photo.key %>">
        <div class="card-trip-infos">
          <div class="d-flex flex-column justify-content-between h-100">
            <div>
              <h2><%= @listing.name %> | <%= @listing.vehicle_type %></h2>
              <p><%= @listing.description %></p>
            </div>
            <div>
              <h2>Where can you find me?</h2>
              <p><%= @listing.country %></p>
              <p><%= @listing.city %></p>
            </div>
          </div>
          <h2 class="card-trip-pricing"><%= @listing.price %> €/day</h2>
        </div>
      </div>
    </div>
    <div class="d-flex flex-column m-4">
      <% @listing.bookings.each do |booking| %>
        <div class="d-flex flex-column card pt-3 px-3 my-3">
          <h2 class="text-center">Reservation by <strong><%= booking.user.first_name %> <%= booking.user.last_name %></strong></h2>
          <div class="d-flex justify-content-around"><h5><em>Start date:</em></h5><p><%= booking.start_date %></p></div>
          <div class="d-flex justify-content-around"><h5><em>End date:</em></h5><p><%= booking.end_date %></p></div>
        </div>
      <% end %>
    </div>
  </div>
</div>



<%= render "../views/footer" %>

app/views/listings/new.html.erb
<%= render user_signed_in? ? "../views/navbar_loggedin" : "../views/navbar_notloggedin" %>

<div class="container">
  <div class="row justify-content-center">
    <div class="col-9 col-lg-6 my-5 text-left">
    <div class="text-center">
      <h1>Add a new WEhicle!</h1>
      <p>✨  🛵  🚀  🛺  🛴  🏎  🛵  🚀  🛺  🛴  🏎   ✨</p>
    </div>

    <%= simple_form_for @listing do |f| %>
      <%= f.input :vehicle_type %>
      <%= f.input :name %>
      <%= f.input :description %>
      <%= f.input :street %>
      <%= f.input :zip %>
      <%= f.input :city %>
      <%= f.input :country %>
      <%= f.input :price %>
      <%= f.input :start_date, as: :date, html5: true %>
      <%= f.input :end_date, as: :date, html5: true %>
      <%= f.input :photo, as: :file %>
      <%= f.button :submit, class: "btn btn-gradient" %>
    <% end %>
    </div>
  </div>
</div>

app/views/listings/show.html.erb
<%= render user_signed_in? ? "../views/navbar_loggedin" : "../views/navbar_notloggedin" %>


<div class="container">
  <h1 class="mt-4"><%= @listing.name %></h1>
  <div class="d-flex">
    <div class="showcarddiv">
      <div class="card-trip rounded">
        <% if @listing.photo.attached? %>
          <img class="card-img-top rounded-top" src="<%= cl_image_path @listing.photo.key %>">
        <% end %>
        <div class="card-trip-infos">
          <div class="d-flex flex-column justify-content-between h-100">
            <div>
              <h2><%= @listing.name %> | <%= @listing.vehicle_type %></h2>
              <p><%= @listing.description %></p>
            </div>
            <div>
              <h2>Where can you find me?</h2>
              <p><%= @listing.country %></p>
              <p><%= @listing.city %></p>
            </div>
          </div>
          <h2 class="card-trip-pricing"><%= @listing.price %> €/day</h2>
        </div>
      </div>
    </div>
    <div class="availability d-flex flex-column align-items-center">
      <div class="flex-column text-align-justify"></div>
      <div id="map"
           style="width: 100%; height: 300px; border-radius: 5px"
           data-markers="<%= @markers.to_json %>"
           data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>">
      </div>
      <div class="mt-3">
        <h2>Availability:</h2>
        <p><%= @listing.start_date %> to <%= @listing.end_date %></p>
      </div>
      <%= simple_form_for [@listing, @booking] do |f| %>
        <%= f.input :start_date, as: :date, html5: true, class: "startdate" %>
        <%= f.input :end_date, as: :date, html5: true, class: "enddate" %>
          <div class="pricefield mb-2 font-weight-bold text-center">
      </div>
        <div id="bookingbtn">
        <%= f.button :submit, class: "btn btn-gradient text-align-center" %>
        </div>
      <% end %>
    </div>
    </div>
  </div>
</div>



<%= render "../views/footer" %>

app/views/pages/home.html.erb
<% yield %>
<%= render user_signed_in? ? "../views/navbar_loggedin" : "../views/navbar_notloggedin" %>

<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.2),rgba(0,0,0,0.2)), url(https://images.unsplash.com/photo-1529313779164-31ef6a34524f?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1950&q=80);">
  <div class="container">
    <h1>WEhicles for <strong>awesome people</strong> with <strong>awesomeness</strong>!</h1>
    <p>Enjoy an experience that you didn't dare to dream about</p>
    <div class="text-center mt-5">
      <a class="btn btn-warning btn-lg"<%= link_to "Explore now!", listings_path %></a>
    </div>
  </div>
</div>

<div class="container-fluid card-container d-flex justify-content-center flex-wrap mt-5">


  <% Listing.all.sample(6).each do |listing| %>
    <a class="card col-3 mx-3 px-0 my-3 border-0" style="text-decoration:none" href="<%= listing_path(listing) %>">
        <% if listing.photo.attached? %>
          <img class="card-img-top" style="height: 300px; object-fit: cover;" src="<%= cl_image_path listing.photo.key %>">
        <% end %>
      <div class="card-infos mx-2">
        <div class="row justify-content-between mt-2 mx-1">
          <h2><%= listing.name %></h2>
          <div class="row justify-content-between mx-1">
            <h3 class="mx-1"><%= listing.price %> €/day</h3>
          </div>
        </div>
        <div class="row justify-content-between mx-1">
          <h5><em><%= listing.city %>, <%= listing.country %></em></h5>
        </div>
        <p class="mx-1"><%= listing.description %></p>
      </div>
    </a>
  <% end %>
</div>




<% yield %>
<%= render "../views/footer" %>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-light alert-dismissible" id="bookingalert" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/users/display.html.erb
<% yield %>
<%= render user_signed_in? ? "../views/navbar_loggedin" : "../views/navbar_notloggedin" %>



<% yield %>
<%= render "../views/footer" %>

app/views/users/settings.html.erb
<% yield %>
<%= render user_signed_in? ? "../views/navbar_loggedin" : "../views/navbar_notloggedin" %>



<% yield %>
<%= render "../views/footer" %>